# Generated by Django 3.1.4 on 2021-09-17 05:41

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('data_type', models.IntegerField(default=1)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=upload.models.upload_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
