# Generated by Django 3.1.4 on 2021-09-17 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20210917_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='title',
            new_name='description',
        ),
        migrations.AddField(
            model_name='dataset',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
