# Generated by Django 3.1.4 on 2021-09-17 06:49

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20210917_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=upload.models.upload_path),
        ),
    ]
